config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  devise_for :users
  root to: "pages#home"
  resources :flats do
    resources :bookings, only: [:create]
  end
  get "my_flats", to: "flats#my_flats"
  get "approve/:flat_id/:id", to: "bookings#approve", as: :approve
  get "my_bookings", to: "bookings#my_bookings"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date?
  validates :number_of_guests, presence: true
  validates :details, presence: true, length: {minimum: 5}

  def end_date_after_start_date?
    if end_date <= start_date
      errors.add :end_date, "must be after start date"
    end
  end
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :city, presence: true
  validates :description, presence: true
  validates :bedrooms, numericality: { only_integer: true }
  validates :number_of_guests, numericality: { only_integer: true }
  validates :price_per_night, numericality: { only_integer: true }
  validates :rating, presence: true

  has_many :bookings, dependent: :destroy

  has_one_attached :photo

  validates :address, presence: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  include PgSearch::Model
  pg_search_scope :search_by_title_city_and_description,
    against: [ :title, :city, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :flats, dependent: :destroy
  has_one_attached :avatar
  has_many :bookings, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :avatar])
  end

  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: [:index, :my_bookings], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^flats$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.new(booking_params)
    @booking.flat = @flat
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to my_bookings_path
    else
      render "flats/show", status: :unprocessable_entity
    end
  end

  def approve
    @flat = Flat.find(params[:flat_id])
    @booking = Booking.find(params[:id])
    @booking.approve = true
    authorize @booking
    @booking.save
    redirect_to flat_path(@flat)
  end

  def my_bookings
    @bookings = current_user.bookings
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :number_of_guests, :details, :user)
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: :index
  # skip_after_action :verify_policy_scoped, only: :index

  def index
    # @flats = policy_scope(Flat)
    @flats = Flat.all
    if params[:query].present?
      @flats = Flat.search_by_title_city_and_description(params[:query])
    end
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { flat: flat }),
        image_url: helpers.asset_url("home.png")
      }
    end
  end

  def show
    authorize @flat
    @markers = [{
                  lat: @flat.latitude,
                  lng: @flat.longitude,
                  info_window: render_to_string(partial: "info_window", locals: { flat: @flat }),
                  image_url: helpers.asset_url("home.png")
                }]
    @booking = Booking.new
    # @bookings = current_user == @flat.user ? @flat.bookings : @flat.bookings.where(guest: current_user)
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    authorize @flat
    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @flat
  end

  def update
    authorize @flat
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    authorize @flat
    @flat.destroy
    redirect_to my_flats_path
  end

  def my_flats
    @flats = current_user.flats
    authorize @flats
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "info_window", locals: { flat: flat }),
        image_url: helpers.asset_url("home.png")
      }
    end
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:title, :city, :description, :bedrooms, :number_of_guests, :price_per_night, :photo, :rating, :address)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    # @flats = policy_scope(Flat)
    @flats = Flat.all
    if params[:query].present?
      @flats = Flat.search_by_title_city_and_description(params[:query])
    else
      @flats = Flat.all
    end
    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window: render_to_string(partial: "/flats/info_window", locals: { flat: flat }),
        image_url: helpers.asset_url("home.png")
      }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_form.html.erb
<div class="row justify-content-center">
  <div class="col-sm-6 col-md-8">
    <%= simple_form_for([flat, booking]) do |f| %>
      <%= f.input :start_date %>
      <%= f.input :end_date %>
      <%= f.input :number_of_guests %>
      <%= f.input :details %>
      <%= f.submit "Book", class: "btn btn-flat", style: "width: 100%" %>
    <% end %>
  </div>
</div>

app/views/bookings/my_bookings.html.erb
<div class="container">
  <h2>My bookings</h2>
  <div class="row justify-content-center m-1">
    <% @bookings.each do |booking| %>
        <div class="card-flat p-3 m-2 ">
          <%= cl_image_tag booking.flat.photo.key %>
          <div class="card-flat-infos">
            <div>
              <h3><%= booking.flat.title %></h3>
              <h2><%= booking.flat.city %></h2>
              <h6>Your host: <%= booking.flat.user.first_name %></h6>
              <% if booking.approve %>
                <h6><strong>This booking was approved</strong></h6>
                <% else %>
                <h6 style="color: red;">This booking is pending approve</h6>
              <% end %>
              <p>From <%= booking.start_date %> to <%= booking.end_date %></p>
              <p>Number of guests: <%= booking.number_of_guests %></p>
              <p>Details: <%= booking.details %></p>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/flats/_form.html.erb
<div class="row justify-content-center">
  <div class="col-12 col-md-6 col-lg-4">
    <%= simple_form_for(@flat) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <%= f.input :title %>
      <%= f.input :city %>
      <%= f.input :address,
                  input_html: {data: {address_autocomplete_target: "address"}, class: "d-none"},
                  wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
                  %>
      <%= f.input :description %>
      <%= f.input :bedrooms %>
      <%= f.input :number_of_guests %>
      <%= f.input :price_per_night %>
      <%= f.input :photo, as: :file %>
      <%= f.input :rating %>
      <%= f.button :submit, class: "btn btn-flat" %>
    <% end %>
  </div>
</div>

app/views/flats/_info_window.html.erb
<div class="card-flat-map">
  <%= cl_image_tag flat.photo.key %>
  <%= link_to flat_path(flat), target: :_blank do %>
    <h3><%= flat.title %></h3>
  <% end %>
  <h5><%= flat.city %></h5>
  <p><%= "⭐️" * flat.rating %></p>
</div>

app/views/flats/edit.html.erb
<div class="container">
  <br>
  <div class="row text-center">
    <h1>Editing flat</h1>
  </div>
  <br>
  <%= render 'form', flat: @flat %>
  <br>
  <hr>
  <div class="row justify-content-evenly">
    <div class="col-4">
      <%= link_to "< Back", flats_path, class: "btn btn-ghost" %>
    </div>
    <div class="col-2">
      <%= link_to "Show", flat_path(@flat), class: "btn btn-ghost" %>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<div class="container">
  <div class="my-3">
    <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a flat"
      %>
      <%= submit_tag "Search", class: "btn btn-flat" %>
    <% end %>
  </div>

  <div style="width: 100%; height: 400px; margin: 3px"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <% if false %>
  PARA OBTENER EL VALOR BUSCADO EN EL SEARCH PRINCIPAL Y PASARLO A MAP CONTROLLER
    <div style="width: 100%; height: 400px; margin: 3px"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-query-value="<%= params[:query] %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <% end %>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @flats.each do |flat| %>
      <div class="col">
        <%= link_to flat_path(flat), class: "card-flat" do %>
          <%= cl_image_tag flat.photo.key %>
          <div class="card-flat-infos h-100">
            <div>
              <h3><%= flat.title %></h3>
              <h2><%= flat.city %></h2>
              <p><%= flat.description %></p>
              <p>Bedrooms: <%= flat.bedrooms %></p>
              <p>Number of guests: <%= flat.number_of_guests %></p>
              <p><%= flat.user.first_name %></p>
              <p><%= "⭐️" * flat.rating %></p>
            </div>
            <h2 class="card-flat-pricing">€ <%= flat.price_per_night %> night</h2>
            <% if flat.user.avatar.attached? %>
              <%= cl_image_tag flat.user.avatar.key, class: "card-flat-user avatar-bordered" %>
            <% else %>
              <%= image_tag "user.png", class: "card-flat-user avatar-bordered" %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/my_flats.html.erb
<div class="container">
  <h1>My flats</h1>
  <div style="width: 100%; height: 400px; margin: 3px"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @flats.each do |flat| %>
      <div class="col">
        <div class="card-flat">
          <%= cl_image_tag flat.photo.key %>
          <div class="card-flat-infos">
            <div>
              <%= link_to flat_path(flat) do %>
                <h3><%= flat.title %></h3>
              <% end %>
              <h2><%= flat.city %></h2>
              <p><%= flat.description %></p>
              <p>Bedrooms: <%= flat.bedrooms %></p>
              <p>Number of guests: <%= flat.number_of_guests %></p>
              <p><%= flat.user.first_name %></p>
              <p><%= "⭐️" * flat.rating %></p>
            </div>
            <h2 class="card-flat-pricing">€ <%= flat.price_per_night %> night</h2>
            <% if flat.user.avatar.attached? %>
              <%= cl_image_tag flat.user.avatar.key, class: "card-flat-user avatar-bordered" %>
            <% else %>
              <%= image_tag "user.png", class: "card-flat-user avatar-bordered" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <br>
  <div class="row text-center">
    <h1>Add a new flat</h1>
  </div>
  <br>
  <%= render 'form', flat: @flat %>
  <br>
  <hr>
  <%= link_to "< Back", flats_path, class: "btn btn-ghost" %>
</div>

app/views/flats/show.html.erb
<div class="container">
  <div class="row align-items-center m-1">
    <div class="col-12 col-md-12 col-lg-6">
      <div class="card-flat p-3 m-2">
        <%= cl_image_tag @flat.photo.key %>
        <div class="card-flat-infos">
          <div>
            <h3><%= @flat.title %></h3>
            <h2><%= @flat.city %></h2>
            <p><%= @flat.description %></p>
            <p>Bedrooms: <%= @flat.bedrooms %></p>
            <p>Number of guests: <%= @flat.number_of_guests %></p>
            <p><%= @flat.user.first_name %></p>
            <p><%= "⭐️" * @flat.rating %></p>
          </div>
          <h2 class="card-flat-pricing">€ <%= @flat.price_per_night %> night</h2>
          <% if @flat.user.avatar.attached? %>
            <%= cl_image_tag @flat.user.avatar.key, class: "card-flat-user avatar-bordered" %>
          <% else %>
            <%= image_tag "user.png", class: "card-flat-user avatar-bordered" %>
          <% end %>
        </div>
        <div class="row">
          <% if policy(@flat).edit? %>
            <div class="col col-3 col-md-2">
              <%= link_to "Edit", edit_flat_path(@flat), class: "btn btn-ghost" %>
            </div>
          <% end %>
          <% if policy(@flat).destroy? %>
            <div class="col col-3 col-md-2">
              <%= link_to "Delete", flat_path(@flat), class: "btn btn-ghost", data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete?"}%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-12 col-lg-6">
      <div class="card-flat p-3 m-2">
        <div style="width: 100%; height: 400px; margin: 3px"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"></div>
      </div>
    </div>
  </div>
    <div class="row align-items-center m-4">
      <div class="col-12 col-md-12 col-lg-6 card-flat p-3 m-2 mx-auto">
        <%= render 'bookings/form', flat: @flat, booking: @booking %>
      </div>
    </div>
  <br>
  <br>
  <hr>
  <% if policy(@flat).edit? %>
    <h2>Bookings</h2>
    <% @flat.bookings.each do |booking| %>
      <div class="card-guest m-4">
        <% if booking.user.avatar.attached? %>
          <%= cl_image_tag booking.user.avatar.key%>
          <% else %>
          <%= image_tag "user.png" %>
        <% end %>
        <div class="card-guest-infos">
          <h2><%= booking.user.first_name %></h2>
          <% if booking.approve %>
            <p>This booking was approved</p>
            <% else %>
            This booking is pending your approve <%= link_to "Approve booking", approve_path(@flat, booking), class: "btn btn-flat", data: {turbo_method: :approve, turbo_confirm: "Are you sure you want to approve?"} %>
          <% end %>
          <p>From <%= booking.start_date %> to <%= booking.end_date %></p>
          <p>Number of guests: <%= booking.number_of_guests %></p>
          <p>Details: <%= booking.details %></p>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ezepdc Airbnb</title>
    <%= favicon_link_tag "airbnb.png" %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="my-3">
    <%= form_with url: flats_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a flat"
      %>
      <%= submit_tag "Search", class: "btn btn-flat" %>
    <% end %>
  </div>

  <div style="width: 100%; height: 400px; margin: 3px"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <% if false %>
  PARA OBTENER EL VALOR BUSCADO EN EL SEARCH PRINCIPAL Y PASARLO A MAP CONTROLLER
    <div style="width: 100%; height: 400px; margin: 3px"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-query-value="<%= params[:query] %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  <% end %>

  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @flats.each do |flat| %>
      <div class="col">
        <%= link_to flat_path(flat), class: "card-flat" do %>
          <%= cl_image_tag flat.photo.key %>
          <div class="card-flat-infos h-100">
            <div>
              <h3><%= flat.title %></h3>
              <h2><%= flat.city %></h2>
              <p><%= flat.description %></p>
              <p>Bedrooms: <%= flat.bedrooms %></p>
              <p>Number of guests: <%= flat.number_of_guests %></p>
              <p><%= flat.user.first_name %></p>
              <p><%= "⭐️" * flat.rating %></p>
            </div>
            <h2 class="card-flat-pricing">€ <%= flat.price_per_night %> night</h2>
            <% if flat.user.avatar.attached? %>
              <%= cl_image_tag flat.user.avatar.key, class: "card-flat-user avatar-bordered" %>
            <% else %>
              <%= image_tag "user.png", class: "card-flat-user avatar-bordered" %>
            <% end %>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <%# <div class="footer-links">

    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div> %>
  <div class="footer-copyright">
    This site was made by <a href="https://github.com/ezepdc" target="_blank">Ezequiel Puyos da Costa</a> <a href="https://github.com/ezepdc" target="_blank"><i class="fab fa-github"></i></a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "airbnb.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Flats", flats_path, class: "nav-link" %>
          </li>
          <li class="nav-item nav-link">
            <strong>Hello, <%= current_user.first_name %></strong>
          </li>
          <li class="nav-item dropdown">
            <% if current_user.avatar.attached? %>
              <%=  cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= image_tag "user.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Add new flat", new_flat_path, class: "dropdown-item" %>
              <%= link_to "My flats", my_flats_path, class: "dropdown-item" %>
              <%= link_to "My bookings", my_bookings_path, class: "dropdown-item" %>
              <%= link_to "Edit my user", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>